version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysqlserver
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:    
      - 3306:3306
    environment:
      MYSQL_DATABASE: movies_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local