version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:    
      - 3306:3306
    environment:
      MYSQL_DATABASE: movies_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - mtt-network
  movie-api-service:
    container_name: movie-api-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    networks:
      - mtt-network
networks:
  mtt-network:
    driver: bridge
